//
//  Datos.swift
//  Hamburguesas
//
//  Created by Nicolás Narria on 12/7/15.
//  Copyright © 2015 Nicolás Narria. All rights reserved.
//

import Foundation
import UIKit

class ColeccionDePaises {
    let paises:[String] = [
        "Afganistán",
        "Albania",
        "Alemania",
        "Andorra",
        "Angola",
        "Anguilla",
        "Antigua y Barbuda",
        "Antillas Holandesas",
        "Arabia Saudí",
        "Argelia",
        "Argentina",
        "Armenia",
        "Aruba",
        "Australia",
        "Austria",
        "Azerbayan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Bélgica",
        "Belice",
        "Benin",
        "Bermudas",
        "Bielorrusia",
        "Bolivia",
        "Bosnia - Herzegovina",
        "Botswana",
        "Brasil",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burma (Myanmar)",
        "Burundi",
        "Bután",
        "Cabo Verde",
        "Camboya",
        "Camerún",
        "Canada",
        "Chad",
        "Chile",
        "China",
        "Chipre",
        "Colombia",
        "Comoros",
        "Congo",
        "Corea del Norte",
        "Corea del Sur",
        "Costa de Marfil",
        "Costa Rica",
        "Croacia",
        "Cuba",
        "Dinamarca",
        "Dominica",
        "Ecuador",
        "Egipto",
        "El Salvador",
        "Emiratos Arabes Unidos",
        "Eritrea",
        "Eslovaquia",
        "Eslovenia",
        "España",
        "Estados Unidos",
        "Estonia",
        "Etiopia",
        "Fiji",
        "Filipinas",
        "Finlandia",
        "Francia",
        "Gabón",
        "Gambia",
        "Georgia",
        "Ghana",
        "Gibraltar",
        "Granada",
        "Grecia",
        "Groenlandia",
        "Guadalupe",
        "Guam",
        "Guatemala",
        "Guayana",
        "Guayana Francesa",
        "Guinea",
        "Guinea Ecuatorial",
        "Guinea-Bissau",
        "Haití",
        "Holanda",
        "Honduras",
        "Hong Kong",
        "Hungría",
        "I. Caimán",
        "I. Cocos (Keeling)",
        "I. Cook",
        "I. Feroe",
        "I. Galápagos",
        "I. Malvinas",
        "I. Marianas del Norte",
        "I. Marshall",
        "I. Reunión",
        "I. Salomón",
        "I. Vírgenes Británicas",
        "I. Vírgenes EEUU",
        "I. Wallis y Futuna",
        "India",
        "Indonesia",
        "Irán",
        "Iraq",
        "Irlanda",
        "Islandia",
        "Israel",
        "Italia",
        "Jamaica",
        "Japón",
        "Jordania",
        "Kazajistán",
        "Kenia",
        "Kirguizistán",
        "Kiribati",
        "Kuwait",
        "Laos",
        "Lesotho",
        "Letonia",
        "Líbano",
        "Liberia",
        "Líbia",
        "Liechtenstein",
        "Lituania",
        "Luxemburgo",
        "Macao",
        "Macedonia",
        "Madagascar",
        "Malasia",
        "Malawi",
        "Maldivas",
        "Mali",
        "Malta",
        "Marruecos",
        "Martinica",
        "Mauricio",
        "Mauritania",
        "México",
        "Micronesia",
        "Moldavia",
        "Mónaco",
        "Mongolia",
        "Montserrat",
        "Mozambique",
        "Namibia",
        "Nauru",
        "Nepal",
        "Nicaragua",
        "Níger",
        "Nigeria",
        "Noruega",
        "Nueva Caledonia",
        "Nueva Zelanda",
        "Omán",
        "Pakistán",
        "Palau",
        "Panamá",
        "Papua Nueva Guinea",
        "Paraguay",
        "Peru",
        "Polinesia Francesa",
        "Polonia",
        "Portugal",
        "Puerto Rico",
        "Qatar",
        "Reino Unido",
        "Rep. Centroafricana",
        "Rep. Checa",
        "Rep. Dominicana",
        "Ruanda",
        "Rumania",
        "Rusia",
        "Sáhara Occidental",
        "Samoa",
        "San Marino",
        "Sao Tomé y Príncipe",
        "Senegal",
        "Seychelles",
        "Sierra Leona",
        "Singapur",
        "Siria",
        "Somalia",
        "Sri Lanka",
        "St. Vicent y Grenadines",
        "St.Kitts & Nevis",
        "Sudán",
        "Suecia",
        "Suiza",
        "Sur Georgia e I. Sandwich",
        "Suráfrica",
        "Surinam",
        "Swazilandia",
        "Tailandia",
        "Taiwán",
        "Tajikistán",
        "Tanzania",
        "Togo",
        "Tonga",
        "Trinidad y Tobago",
        "Túnez",
        "Turkmenistán",
        "Turquia",
        "Tuvalu",
        "Ucrania",
        "Uganda",
        "Uruguay",
        "Uzbekistán",
        "Vanuatu",
        "Vaticano",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Yibuti",
        "Yugoslavia",
        "Zaire",
        "Zambia",
        "Zimbabwe"
    ]
    
    func obtenPais()->String {
        let index: Int = Int(arc4random()) % self.paises.count
        
        return self.paises[index]
    }
}

class ColeccionDeHamburguesas {
    let hamburguesas: [String] = [
        "La rossini",
        "Hamburguesa 777",
        "Fleurburger 5000",
        "The burger Tri-Beef",
        "The Richard Nouveau Burger",
        "Le Burger Extravagante",
        "La Douche Hamburguesa",
        "Hamburguesa Leia",
        "Hamburguesa Pan Solo",
        "Hamburguesa Darth Vader",
        "Hamburguesa C3PO",
        "Hamburguesa Chewaka",
        "Big mac",
        "Cuarto de libra con queso",
        "Macnifica",
        "Hamburguesa regular",
        "Hamburguesa regular con queso",
        "Mac queso",
        "Big Tasty",
        "Cuarto de libra doble con queso",
        "Mac pollo deluxe",
        "Pechuga Classic",
        "Pechuga club bacon",
        "Pechuga honey mustard",
        "Mac trio de pollo",
        "Cebolla pochada",
        "Ternera Blanca",
        "Asturiana",
        "Buey gallego",
        "Valles esla"
    ]
    
    func obtenHamburguesa( )->String {
        let index: Int = Int(arc4random()) % self.hamburguesas.count
        
        return self.hamburguesas[index]
    }
}



struct Colores {    
    func regresaColorAleatorio () ->UIColor {
        
        let redAleatorio = CGFloat(Int(arc4random()) % 255)/255.0
        let greenAleatorio = CGFloat(Int(arc4random()) % 255)/255.0
        let blueAleatorio = CGFloat(Int(arc4random()) % 255)/255.0
        
        return UIColor(red:redAleatorio, green:greenAleatorio, blue:blueAleatorio, alpha: 1)
    }
}
